name: sakulegacy
description: "Happy photo for everybody - Fridge Magnet Specialist"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # --- Senjata Tambahan Saku Legacy ---
  camera: ^0.11.0+1        # Untuk guna kamera phone
  path_provider: ^2.1.2    # Untuk simpan fail imej sementara
  screenshot: ^3.0.0       # Untuk gabung Gambar + Frame jadi satu fail
  http: ^1.2.1             # Untuk hantar gambar ke Telegram Bot
  image_picker: ^1.0.7     # Optional: Jika nak ambil gambar dari galeri

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/frames/