name: aquamonitor
description: "Smart Water Usage Monitoring System - AquaMonitor"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # 1. Untuk sambung ke Database UniSZA (API PHP)
  http: ^1.6.0

  # 2. Untuk Graf di skrin Dashboard & Statistics
  fl_chart: 0.65.0

  # 3. Untuk format tarikh di skrin History
  intl: ^0.19.0

  # 4. Fungsi QR Scanner untuk Pair/Unpair Device
  mobile_scanner: ^5.1.0

  # 5. Icons untuk UI
  cupertino_icons: ^1.0.8

  # 6. Shared preferences
  shared_preferences: ^2.3.2

  # Ditambah untuk mengawal & membaiki skrin loading (Splash Screen) yang kemek
  flutter_native_splash: ^2.4.0

  # 7. Ditambah untuk fungsi snap / pilih gambar dari galeri
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Ditambah untuk menukar App Icon secara automatik
  flutter_launcher_icons: ^0.13.1

# Konfigurasi penjana ikon aplikasi (Ikon APK menggunakan logoo.png)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logoo.png"

  # Memisahkan latar belakang dan logo utama untuk Android Oreo ke atas (Fix Kemek)
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logoo.png"
  min_sdk_android: 21

# Konfigurasi skrin loading semasa mula buka app (Splash Screen menggunakan logoo.png)
flutter_native_splash:
  color: "#F3F9FF"
  image: "assets/logoo.png"

  android_12:
    image: "assets/logoo.png"
    color: "#F3F9FF"

flutter:
  uses-material-design: true

  # KEMASKINI: Dua-dua fail imej dimasukkan supaya login screen (logo.png) tak error
  assets:
    - assets/logo.png
    - assets/logoo.png